swagger: "2.0"
info:
  description: "This is an OpenAPI for Database Connectivity"
  version: "1.0.0"
  title: "Database Connections"
  termsOfService: "IU <todo>"
  contact:
    email: "joshish@iu.edu"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/cloudmesh/v1/database/connection"
tags:
- name: "database connection"
  description: "Database Connection"
  externalDocs:
    description: "Connect to and disconnect from databases"
    url: "http://swagger.io"
schemes:
- "http"
consumes:
  - "application/json"
produces:
  - "application/json"
paths:
  /connections:
    get:
      tags:
      - "database connection"
      summary: "List all open connections"
      description: "List open connections"
      operationId: "cloudmesh.databases.Provider.get_connections"
      produces:
      - "application/json"
      responses:
        200:
          description: "successfully listed open connections"
          schema:
            $ref: "#/definitions/databaseConnection"
        400:
          description: "Invalid status value"
  /connection/{dbId}:
    post:
      tags:
      - "database connection"
      summary: "Connect to a database"
      description: ""
      operationId: "cloudmesh.database.Provider.connect_database"
      produces:
      - "application/json"
      parameters:
      - name: "dbId"
        in: "path"
        description: "ID of database to be connected"
        required: true
        type: "string"
      - name: "JDBCConnectionString"
        in: "query"
        description: "JDBC Connection String"
        required: true
        type: "string"
      - name: "username"
        in: "query"
        description: "Username"
        type: "string"
      - name: "password"
        in: "query"
        description: "Password"
        type: "string"
      responses:
        200:
          description: "successfully connected to database"
          schema:
            $ref: "#/definitions/databaseConnection"
        400:
          description: "Invalid ID supplied"
        401:
          description: "Invalid credentials"
        405:
          description: "Invalid input"
    delete:
      tags:
      - "database connection"
      summary: "Disconnects from a database, and close connection"
      description: "Disconnect from a database, and close connection"
      operationId: "cloudmesh.database.Provider.disconnect_database"
      produces:
      - "application/json"
      parameters:
      - name: "dbId"
        in: "path"
        required: true
        type: "string"
      responses:
        200:
          description: "successfully disconnected"
          schema:
            $ref: "#/definitions/databaseConnection"
        400:
          description: "Invalid ID supplied"
        404:
          description: "Database Connection String not found"
definitions:
  databaseConnection:
    type: "object"
    required:
    - "dbId"
    properties:
      dbId:
        type: "string"
